[package]
name = "kiro-client"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
egui_plot = "0.31.0"
humantime = "2.2.0"
rand = "0.9.0"
twink = { version = "1.1.3", features = ["log"] }
